# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VanGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VanGo
	# add pods for desired Firebase products
	# https://firebase.google.com/docs/ios/setup#available-pods
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

	# Optionally, include the Swift extensions if you're using Swift.
	pod 'FirebaseFirestoreSwift'

  target 'VanGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VanGoUITests' do
    # Pods for testing
  end

end
